export const data = {
  brand: {
    type: "multi-select",
    label: "Brand",
    values: [
      "Apple",
      "Samsung",
      "Sony",
      "Bose",
      "HP",
      "Dell",
      "Nest",
      "Ring",
      "Fitbit",
      "Garmin",
      "Canon",
      "Nikon",
      "IKEA",
      "West Elm",
      "Crate & Barrel",
      "Herman Miller",
      "Ashley Furniture",
    ],
  },
  category: {
    type: "multi-select",
    label: "Category",
    values: [
      "Smart Home Devices",
      "Mobile Phones",
      "Wearable Technology",
      "Tablets",
      "Audio Equipment",
      "Gaming Consoles",
      "Laptops",
      "Home Security Systems",
      "Electronic Personal Care Devices",
      "Cameras and Photography Equipment",
      "Living Room Furniture",
      "Bedroom Furniture",
      "Storage Solutions",
      "Kitchen and Bar Furniture",
      "Outdoor Furniture",
      "Dining Room Furniture",
      "Home Office Furniture",
      "Accent Furniture",
      "Kids' Furniture",
    ],
  },
  price: {
    type: "range",
    label: "Price",
    values: [0, 6500],
  },
  discountPercentage: {
    type: "single-select",
    label: "Discount Percentage",
    values: [0, 10, 20, 30, 40, 50],
  },
  rating: {
    type: "rating",
    label: "Rating",
    values: [1, 2, 3, 4, 5],
  },
  colors: {
    type: "multi-select",
    label: "Colors",
    values: [
      "red",
      "orange",
      "yellow",
      "green",
      "blue",
      "purple",
      "pink",
      "brown",
      "black",
      "white",
      "gray",
      "silver",
      "gold",
      "teal",
      "coral",
      "salmon",
      "hotpink",
      "lime",
      "indigo",
      "tomato",
      "orangered",
      "palevioletred",
      "seagreen",
      "wheat",
      "aqua",
      "dodgerblue",
      "deeppink",
      "chartreuse",
      "fuchsia",
      "lemonchiffon",
      "paleturquoise",
      "mediumorchid",
      "papayawhip",
      "palegreen",
      "mediumvioletred",
      "plum",
      "darkorange",
      "mediumspringgreen",
      "maroon",
      "greenyellow",
    ],
  },
};
